baseURL = "https://www.relativeflow.com/"
languageCode = "en"
title = "RelativeFlow"
theme = "hugo-theme-cactus-plus"

[params]
  name = "RelativeFlow"
  description = "network | @relativeflow"
  bio = "network | @relativeflow"
  twitter = "relativeflow"
  enableRSS = true

  disqusShortname = "relativeflow"
  enableDisqus = true

  customCSS = ["css/fixes.css"]
 
  iconFont = "font-awesome"

[social]
  twitter-square = "https://twitter.com/relativeflow"
  github-square = "https://github.com/paulowen"
